import { Metadata } from "next";

export const metadata:Metadata = {
title:{
  default:"Next.js - CodeEvolution",
  template:"%s | Codevolution",
},
description:'Generated by Next.js',
}

export default function RootLayout({
  children,
}:{
  children:React.ReactNode
}){
  return (
    <html>
      <body>
        <header style={{backgroundColor:"LightBlue",padding:"1rem"}}>
        <p>Header</p>
        </header>
        {children}
        <footer style={{backgroundColor:"ghostWhite",padding:"1rem"}}>
        <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}

// when you visit the URL the metadate can be read from the dynamic route object based on the page
// To set an unique / consistent title of metadata.
// Never use absolute title in the metadata object, use generateMetadata instead.
// If you want to set a default title, use the template property in the metadata object. 