import { Metadata } from "next";

export const metadata:Metadata = {
title:{
  default:"Next.js - CodeEvolution",
  template:"%s | Codevolution",
  absolute:""  //This gives the user to assign absolute title for the pages moving out of an assigned template.
},
description:'Generated by Next.js',
}

export default function RootLayout({
  children,
}:{
  children:React.ReactNode
}){
  return (
    <html>
      <body>
        <header style={{backgroundColor:"LightBlue",padding:"1rem"}}>
        <p>Header</p>
        </header>
        {children}
        <footer style={{backgroundColor:"ghostWhite",padding:"1rem"}}>
        <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}

// when you visit the URL 